Repository Liatoshynsky-Foundation/lf-client, pull requests merged in 2025-09, with the labels that each got.

#562 feat: create new modal component
  app/shared/components/backdrop-component/BackdropComponent.styles.ts
  app/shared/components/modal-component/ModalComponent.test.tsx
  app/shared/components/modal-component/ModalComponent.tsx
  app/shared/components/paper-component/PaperComponent.styles.ts
Labels: frontend, feature

#567 chore: create new template to create new issues/tasks
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, config

#556 Implemented payment details switcher
  app/shared/components/blocks/payment-details/PaymentDetails.styles.ts
  app/shared/components/blocks/payment-details/PaymentDetails.test.tsx
  app/shared/components/blocks/payment-details/PaymentDetails.tsx
  app/shared/components/blocks/payment-details/constants.ts
  public/icons/content-copy.svg
Labels: frontend, feature

#563 feat: implement year with line component
  app/shared/components/design-system/all-components/theme/Theme.ts
  app/shared/components/year-with-line/YearWithLine.styles.tsx
  app/shared/components/year-with-line/YearWithLine.test.tsx
  app/shared/components/year-with-line/YearWithLine.tsx
Labels: frontend, feature

#560 Create donation form
  app/shared/components/design-system/all-components/button-group/ButtonGroup.styles.ts
  app/shared/components/design-system/all-components/theme/Theme.ts
  app/shared/components/design-system/all-components/theme/colors.ts
  app/shared/components/forms/donation-form/DonationForm.styles.ts
  app/shared/components/forms/donation-form/DonationForm.test.tsx
  app/shared/components/forms/donation-form/DonationForm.tsx
  app/types/types/common.types.ts
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, feature

#564 Add reusable quote component
  app/shared/components/excerpt-block/ExcerptBlock.styles.ts
  app/shared/components/excerpt-block/ExcerptBlock.test.tsx
  app/shared/components/excerpt-block/ExcerptBlock.tsx
  public/icons/quote.svg
Labels: frontend, feature

#578 chore: update bugs template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/quick_bug.md
Labels: documentation, enhancement, config

#579 (SP: 1) Implemented actions help section
  app/[lang]/support-us/page.test.tsx
  app/[lang]/support-us/page.tsx
  app/shared/components/blocks/actions-help/ActionsHelp.consts.ts
  app/shared/components/blocks/actions-help/ActionsHelp.styles.ts
  app/shared/components/blocks/actions-help/ActionsHelp.test.tsx
  app/shared/components/blocks/actions-help/ActionsHelp.tsx
  app/shared/components/design-system/all-components/button-card/ButtonCard.styles.ts
  app/shared/components/design-system/all-components/button-card/ButtonCard.test.tsx
  app/shared/components/design-system/all-components/button-card/ButtonCard.tsx
  app/shared/components/design-system/all-components/text-card/TextCard.tsx
  public/icons/arrow-down-right.svg
Labels: frontend, feature

#565 Privacy Policy page
  app/[lang]/privacy-policy/page.test.tsx
  app/[lang]/privacy-policy/page.tsx
  app/lib/utils/getDocKey.test.ts
  app/lib/utils/getDocKey.ts
  app/shared/components/blocks/privacy-policy/hero-section/PrivacyHeroSection.styles.ts
  app/shared/components/blocks/privacy-policy/hero-section/PrivacyHeroSection.test.tsx
  app/shared/components/blocks/privacy-policy/hero-section/PrivacyHeroSection.tsx
  app/shared/components/blocks/privacy-policy/intro-section/IntroSection.styles.tsx
  app/shared/components/blocks/privacy-policy/intro-section/IntroSection.test.tsx
  app/shared/components/blocks/privacy-policy/intro-section/IntroSection.tsx
  app/shared/components/blocks/privacy-policy/policy-content/PolicyContent.test.tsx
  app/shared/components/blocks/privacy-policy/policy-content/PolicyContent.tsx
  app/shared/components/blocks/privacy-policy/policy-section/PolicySection.styles.tsx
  app/shared/components/blocks/privacy-policy/policy-section/PolicySection.test.tsx
  app/shared/components/blocks/privacy-policy/policy-section/PolicySection.tsx
  app/shared/components/list-item/ListItem.tsx
  app/validators/pagesSchemas/pages/privacy-policy.schema.ts
Labels: frontend, feature

#577 Responsive Ellipsis
  app/shared/components/enhanced-table/EnhancedTable.tsx
  app/shared/components/enhanced-table/collapsible-row/CollapsibleDataRow.tsx
  app/shared/components/enhanced-table/collapsible-row/CollapsibleRow.styles.ts
  app/shared/components/enhanced-table/collapsible-row/CollapsibleRow.test.tsx
  app/shared/components/enhanced-table/collapsible-row/CollapsibleRow.tsx
  app/shared/components/tables/CompositionTable/MusicTableCells.styles.ts
  app/shared/components/tables/CompositionTable/MusicTableCells.tsx
  app/shared/components/tables/CompositionTable/MusicTableSelection.tsx
  app/shared/components/tables/CompositionTable/tableColumnWidth.ts
Labels: feature, responsivness

#582 Update scroll behavior and design of the header
  app/constants/index.ts
  app/shared/components/Footer/Footer.tsx
  app/shared/components/Header/Header.styles.ts
  app/shared/components/Header/Header.test.tsx
  app/shared/components/Header/Header.tsx
  app/shared/components/Header/RightActionsPanel/RightActionsPanel.styles.ts
  app/shared/components/Header/RightActionsPanel/RightActionsPanel.tsx
  app/shared/components/Header/SupportButton/SupportButton.styles.ts
  app/shared/components/Header/SupportButton/SupportButton.test.tsx
  app/shared/components/Header/SupportButton/SupportButton.tsx
  app/shared/components/design-system/all-components/navigation-bar/dekstop-nav/DesktopNav.styles.ts
  app/shared/components/design-system/all-components/navigation-bar/mobile-nav/MobileNav.styles.ts
  app/shared/components/design-system/all-components/navigation-bar/mobile-nav/MobileNav.tsx
  app/shared/components/design-system/all-components/theme/colors.ts
  app/shared/hooks/use-hide-header/useHideHeader.test.tsx
  app/shared/hooks/use-hide-header/useHideHeader.tsx
Labels: bug, frontend, refactoring

#581 Implemented Support Foundation section
  app/[lang]/support-us/page.test.tsx
  app/[lang]/support-us/page.tsx
  app/shared/components/blocks/payment-details/PaymentDetails.styles.ts
  app/shared/components/blocks/support-foundation/SupportFoundation.styles.ts
  app/shared/components/blocks/support-foundation/SupportFoundation.test.tsx
  app/shared/components/blocks/support-foundation/SupportFoundation.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, feature

#572 Implement Modal Window for notes files retrieval
  app/[lang]/contacts/ContactsInfo/ContactsInfo.tsx
  app/[lang]/media-about-us/page.tsx
  app/shared/components/blocks/terms-intro/TermsIntro.style.ts
  app/shared/components/blocks/terms-intro/TermsIntro.tsx
  app/shared/components/cookie-modal/preferances/CookiePreferencesModal.test.tsx
  app/shared/components/design-system/all-components/logo/Logo.tsx
  app/shared/components/forms/contact-form/ContactForm.test.tsx
  app/shared/components/forms/contact-form/ContactForm.tsx
  app/shared/components/get-notes-modal/GetNotesModal.styles.ts
  app/shared/components/get-notes-modal/GetNotesModal.test.tsx
  app/shared/components/get-notes-modal/GetNotesModal.tsx
  app/shared/components/get-notes-modal/notes-confirmation-modal/NotesConfirmModal.styles.ts
  app/shared/components/get-notes-modal/notes-confirmation-modal/NotesConfirmModal.test.tsx
  app/shared/components/get-notes-modal/notes-confirmation-modal/NotesConfirmModal.tsx
  app/shared/components/get-notes-modal/notes-list-modal/NotesListModal.styles.ts
  app/shared/components/get-notes-modal/notes-list-modal/NotesListModal.test.tsx
  app/shared/components/get-notes-modal/notes-list-modal/NotesListModal.tsx
  app/shared/components/get-notes-modal/notes-list-modal/note-list-item/NoteListItem.styles.ts
  app/shared/components/get-notes-modal/notes-list-modal/note-list-item/NoteListItem.tsx
  app/shared/components/get-notes-modal/notes-list-modal/note-list-item/NoteListitem.test.tsx
  app/types/enums/getNotes.enums.ts
  app/types/types/getNotes.types.ts
  i18n/messages/en.json
  i18n/messages/uk.json
  public/images/signature.svg
Labels: frontend, feature

#590 Build the complete 'Terms of use the site' page using existing components
  app/[lang]/terms/page.tsx
  app/lib/utils/tiptapHelpers.test.tsx
  app/lib/utils/tiptapHelpers.ts
  app/shared/components/blocks/terms-intro/TermsIntro.test.tsx
  app/shared/components/blocks/terms-intro/TermsIntro.tsx
  app/shared/components/blocks/terms-of-use/TermsOfUse.style.ts
  app/shared/components/blocks/terms-of-use/TermsOfUse.test.tsx
  app/shared/components/blocks/terms-of-use/TermsOfUse.tsx
  app/shared/components/blocks/terms-of-use/terms-content/TermsContent.test.tsx
  app/shared/components/blocks/terms-of-use/terms-content/TermsContent.tsx
  app/shared/components/blocks/terms-of-use/terms-content/button-content-block/ButtonContentBlock.styles.ts
  app/shared/components/blocks/terms-of-use/terms-content/button-content-block/ButtonContentBlock.test.tsx
  app/shared/components/blocks/terms-of-use/terms-content/button-content-block/ButtonContentBlock.tsx
  app/shared/components/blocks/terms-of-use/terms.const..ts
  app/shared/components/design-system/all-components/content-block/ContentBlock.styles.ts
  app/shared/components/design-system/all-components/content-block/ContentBlock.tsx
  app/shared/components/list-item/ListItem.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
  public/icons/arrow-up-right.svg
  public/images/retro-collage.jpg
Labels: frontend, feature

#604 Fixed image placeholder
  app/shared/components/design-system/all-components/person-card/PersonCard.tsx
Labels: bug, enhancement, frontend

#605 Updated validation logic for donation form
  app/shared/components/forms/donation-form/DonationForm.styles.ts
  app/shared/components/forms/donation-form/DonationForm.test.tsx
  app/shared/components/forms/donation-form/DonationForm.tsx
Labels: enhancement, frontend, validation

#633 Fixed rendering on research and privacy policy pages
  app/[lang]/(pages)/privacy-policy/page.tsx
  app/[lang]/(pages)/research/page.tsx
  app/shared/components/blocks/privacy-policy/policy-content/PolicyContent.test.tsx
  app/shared/components/blocks/privacy-policy/policy-content/PolicyContent.tsx
  app/shared/components/list-item/ListItem.tsx
  app/types/page/research.types.ts
  eslint.config.mjs
Labels: bug
