Repository Liatoshynsky-Foundation/lf-client, pull requests merged in 2025-06, with the labels that each got.

#160 Implemented 'DonationButton'
  app/shared/components/Footer/DonationButton/DonationButton.test.tsx
  app/shared/components/Footer/DonationButton/DonationButton.tsx
  app/shared/components/Footer/Footer.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
  public/icons/donation-button.svg
Labels: frontend, UI/UX, feature

#177 Update user link in readme file
  README.md
Labels: documentation

#195 (SP:3) Create MenuItem element aligned with design system
  app/shared/components/design-system/all-components/menu-item/MenuItem.styles.ts
  app/shared/components/design-system/all-components/menu-item/MenuItem.test.jsx
  app/shared/components/design-system/all-components/menu-item/MenuItem.tsx
  public/icons/check-icon.svg
Labels: frontend, feature, design system

#191 Added aliases for path and updated throught the project
  app/[lang]/layout.tsx
  app/api/contact/route.ts
  app/lib/utils/apiResponse.test.ts
  app/lib/utils/validateContactData.test.ts
  app/shared/components/Footer/DonationButton/DonationButton.tsx
  app/shared/components/Footer/Footer.test.tsx
  app/shared/components/Footer/Footer.tsx
  app/shared/components/Footer/FooterContactInfo/FooterContactInfo.test.tsx
  app/shared/components/Footer/FooterContactInfo/FooterContactInfo.tsx
  app/shared/components/Footer/FooterCopyrights/FooterCopyrights.tsx
  app/shared/components/Header/AudioPlayer/AudioPlayerPopover/AudioPlayerPopover.tsx
  jest.config.ts
  middleware.ts
  tsconfig.json
Labels: frontend, feature

#203 Implement 'Contact us' button
  app/shared/components/Footer/Footer.tsx
  app/shared/components/Footer/FooterContactAndSupport/ContactUsButton/ContactUsButton.test.tsx
  app/shared/components/Footer/FooterContactAndSupport/ContactUsButton/ContactUsButton.tsx
  app/shared/components/Footer/FooterContactAndSupport/DonationButton/DonationButton.test.tsx
  app/shared/components/Footer/FooterContactAndSupport/DonationButton/DonationButton.tsx
  app/shared/components/Footer/FooterContactAndSupport/FooterContactAndSupport.styles.ts
  app/shared/components/Footer/FooterContactAndSupport/FooterContactAndSupport.test.tsx
  app/shared/components/Footer/FooterContactAndSupport/FooterContactAndSupport.tsx
  app/shared/components/Footer/FooterContactAndSupport/types.ts
  i18n/messages/en.json
  i18n/messages/uk.json
  public/icons/mail-icon.svg
Labels: frontend, UI/UX, feature

#206 Implemented SectionTitle component
  app/[lang]/layout.tsx
  app/shared/components/section-title/SectionTitle.styles.ts
  app/shared/components/section-title/SectionTitle.test.tsx
  app/shared/components/section-title/SectionTitle.tsx
  public/icons/ellipse.svg
Labels: frontend, UI/UX, feature

#209 Implement support button in header
  app/shared/components/Header/Header.tsx
  app/shared/components/Header/SupportButton/SupportButton.test.tsx
  app/shared/components/Header/SupportButton/SupportButton.tsx
  app/shared/components/design-system/all-components/button/Button.styles.ts
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, feature

#211 (SP:1) Create Switch element aligned with design system
  app/shared/components/design-system/all-components/switch/Switch.styles.ts
  app/shared/components/design-system/all-components/switch/Switch.test.tsx
  app/shared/components/design-system/all-components/switch/Switch.tsx
Labels: frontend, feature, design system

#210 Combined footer
  app/[lang]/layout.tsx
  app/shared/components/Footer/Footer.styles.ts
  app/shared/components/Footer/Footer.test.tsx
  app/shared/components/Footer/Footer.tsx
  app/shared/components/Footer/FooterContactAndSupport/FooterContactAndSupport.styles.ts
  app/shared/components/Footer/FooterContactInfo/FooterContactInfo.styles.ts
  app/shared/components/Footer/FooterCopyrights/FooterCopyrights.styles.ts
  app/shared/components/Footer/FooterNavigation/FooterNavigation.styles.ts
  app/shared/components/Footer/__snapshots__/Footer.test.tsx.snap
  public/images/footer-img.svg
  public/images/softserve-academy.svg
Labels: frontend, feature

#223 (SP: 0,5) Fix problems with ESLint
  .branchlintrc.config.js
  .github/workflows/ci-pr-to-develop.yml
  app/[lang]/[...unknown-route]/page.tsx
  app/config/index.ts
  app/constants/index.ts
  app/constants/typography.ts
  app/constants/validation.ts
  app/global.d.ts
  app/lib/utils/apiResponse.ts
  app/lib/utils/audioPlayer.ts
  app/lib/utils/errorHelper.test.ts
  app/lib/utils/errorHelper.ts
  app/lib/utils/validateRequestData.test.ts
  app/lib/utils/validateRequestData.ts
  app/middleware/logger/logger.test.ts
  app/shared/components/design-system/all-components/breadcrumbs/BreadCrumbsClient.tsx
  app/shared/components/design-system/all-components/checkbox/Checkbox.styles.ts
  app/shared/components/design-system/all-components/chip/Chip.tsx
  app/shared/components/design-system/all-components/dropdown-menu/DropdownMenu.style.ts
  app/shared/components/design-system/all-components/link/CustomLink.tsx
  app/shared/components/design-system/all-components/person-card/PersonCard.styles.ts
  app/shared/components/design-system/all-components/slider/Slider.styles.ts
  app/shared/components/design-system/all-components/text-field/CustomTextField.styles.ts
  app/shared/components/design-system/all-components/tooltip/Tooltip.styles.ts
  app/types/types/paramsWithLanguage.ts
  commitlint.config.js
  eslint.config.mjs
  i18n/routing.ts
  lint-staged.config.js
  package-lock.json
  package.json
Labels: bug, config, dependencies

#220 Implement `Foundation Team` block
  app/shared/components/FoundationTeam/FoundationTeam.styles.ts
  app/shared/components/FoundationTeam/FoundationTeam.test.tsx
  app/shared/components/FoundationTeam/FoundationTeam.tsx
  app/shared/components/design-system/all-components/person-card/PersonCard.styles.ts
  app/shared/components/design-system/all-components/person-card/PersonCard.test.tsx
  app/shared/components/design-system/all-components/person-card/PersonCard.tsx
  public/images/foundation-team/iryna-tykova.jpg
  public/images/foundation-team/maria_hurska.jpg
  public/images/foundation-team/tetyana-homon.png
  public/images/light-logo.svg
Labels: frontend, UI/UX, feature

#214 (SP: ) Create 'LiatoshynskyOffice' component
  app/[lang]/layout.tsx
  app/[lang]/page.test.tsx
  app/[lang]/page.tsx
  app/constants/index.ts
  app/shared/components/Footer/Footer.test.tsx
  app/shared/components/Footer/__snapshots__/Footer.test.tsx.snap
  app/shared/components/Liatoshynsky-office/LiatoshynskyOffice.styles.ts
  app/shared/components/Liatoshynsky-office/LiatoshynskyOffice.test.tsx
  app/shared/components/Liatoshynsky-office/LiatoshynskyOffice.tsx
  app/shared/components/Liatoshynsky-office/office-media/OfficeMedia.styles.ts
  app/shared/components/Liatoshynsky-office/office-media/OfficeMedia.test.tsx
  app/shared/components/Liatoshynsky-office/office-media/OfficeMedia.tsx
  app/shared/components/Quote/Quote.styles.ts
  app/shared/components/design-system/all-components/logo/Logo.test.tsx
  app/shared/components/design-system/all-components/logo/Logo.tsx
  app/shared/components/design-system/all-components/theme/Theme.ts
  app/types/types/officeMedia.ts
  i18n/messages/en.json
  i18n/messages/uk.json
  public/images/lf-office-1.png
  public/images/lf-office-2.png
  public/images/lf-office-3.png
  public/images/logo.svg
Labels: frontend, UI/UX, feature

#221 Implemented ImageWithCaption component
  app/lib/utils/generateSizesAttribute.test.ts
  app/lib/utils/generateSizesAttribute.ts
  app/shared/components/image-with-caption/ImageWithCaption.styles.ts
  app/shared/components/image-with-caption/ImageWithCaption.test.tsx
  app/shared/components/image-with-caption/ImageWithCaption.tsx
  app/types/types/common.types.ts
Labels: frontend, UI/UX, feature

#231 (SP: 0,5) Fix problem with images and locale in stage
  Dockerfile
  app/shared/components/Footer/FooterCopyrights/FooterCopyrights.styles.ts
  app/shared/components/Footer/__snapshots__/Footer.test.tsx.snap
  app/shared/components/Header/AudioPlayer/AudioPlayerPopover/AudioPlayerPopover.tsx
  app/shared/components/Header/Header.tsx
  i18n/routing.ts
Labels: bug, UI/UX, DevOps

#234 Fix footer position
  app/[lang]/layout.tsx
Labels: bug, frontend

#233 Implemented `FoundationFounders` section
  app/[lang]/page.test.tsx
  app/[lang]/page.tsx
  app/shared/components/FoundationFounders/FoundationFounders.styles.ts
  app/shared/components/FoundationFounders/FoundationFounders.test.tsx
  app/shared/components/FoundationFounders/FoundationFounders.tsx
  app/shared/components/FoundationFounders/FoundationTeam/FoundationTeam.styles.ts
  app/shared/components/FoundationFounders/FoundationTeam/FoundationTeam.test.tsx
  app/shared/components/FoundationFounders/FoundationTeam/FoundationTeam.tsx
  app/shared/components/FoundationFounders/FoundationWasCreated/FoundationWasCreated.styles.ts
  app/shared/components/FoundationFounders/FoundationWasCreated/FoundationWasCreated.test.tsx
  app/shared/components/FoundationFounders/FoundationWasCreated/FoundationWasCreated.tsx
  app/shared/components/FoundationTeam/FoundationTeam.styles.ts
  app/shared/components/FoundationWasCreated/FoundationWasCreated.test.tsx
  app/shared/components/FoundationWasCreated/FoundationWasCreated.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, UI/UX, feature

#232 add `OpenTechLogo` component with support for academy and default logos
  app/shared/components/Footer/Footer.tsx
  app/shared/components/Footer/__snapshots__/Footer.test.tsx.snap
  app/shared/components/design-system/all-components/link/NextLink.tsx
  app/shared/components/design-system/all-components/open-tech-logo/OpenTechLogo.styles.tsx
  app/shared/components/design-system/all-components/open-tech-logo/OpenTechLogo.test.tsx
  app/shared/components/design-system/all-components/open-tech-logo/OpenTechLogo.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
  public/images/opentech-academy.svg
  public/images/opentech.svg
  public/images/softserve-academy.svg
Labels: frontend, UI/UX, feature, design system, test

#239 Implemented OurMission block
  app/[lang]/layout.tsx
  app/[lang]/page.test.tsx
  app/[lang]/page.tsx
  app/shared/components/FoundationFounders/FoundationFounders.styles.ts
  app/shared/components/Liatoshynsky-office/LiatoshynskyOffice.styles.ts
  app/shared/components/image-with-caption/ImageWithCaption.styles.ts
  app/shared/components/image-with-caption/ImageWithCaption.tsx
  app/shared/components/list-item/ListItem.styles.ts
  app/shared/components/list-item/ListItem.test.tsx
  app/shared/components/list-item/ListItem.tsx
  app/shared/components/our-mission/OurMission.styles.ts
  app/shared/components/our-mission/OurMission.test.tsx
  app/shared/components/our-mission/OurMission.tsx
  app/shared/components/section-title/SectionTitle.styles.ts
  app/shared/components/section-title/SectionTitle.test.tsx
  app/shared/components/section-title/SectionTitle.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
  public/images/our-mission/tetiana-homon-big.jpg
  public/images/our-mission/tetiana-homon-small.jpg
Labels: frontend, UI/UX, feature

#273 Implement Our Goals block
  app/[lang]/page.test.tsx
  app/[lang]/page.tsx
  app/shared/components/our-goals/OurGoals.styles.ts
  app/shared/components/our-goals/OurGoals.test.tsx
  app/shared/components/our-goals/OurGoals.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, feature

#279 Centralize Styling for DropdownMenu
  app/shared/components/design-system/all-components/dropdown-menu/DropdownMenu.style.ts
  app/shared/components/design-system/all-components/dropdown-menu/DropdownMenu.tsx
  app/shared/components/design-system/all-components/theme/Theme.ts
Labels: frontend, UI/UX, design system

#287 (SP:1) Implemente 'What are we doing?' block
  app/[lang]/page.test.tsx
  app/[lang]/page.tsx
  app/shared/components/what-we-do/WhatWeDo.styles.ts
  app/shared/components/what-we-do/WhatWeDo.test.tsx
  app/shared/components/what-we-do/WhatWeDo.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, feature

#291 Implemented emotion cache
  app/[lang]/layout.tsx
  app/shared/components/emotion-provider/EmotionProvider.test.tsx
  app/shared/components/emotion-provider/EmotionProvider.tsx
  package-lock.json
Labels: frontend, feature

#272 (SP: 0,5) Hotfix: modified eslint config file for removing carriage return error
  eslint.config.mjs
Labels: hotfix

#293 Feature/243/implement title and quote block
  app/[lang]/layout.tsx
  app/[lang]/research/page.test.tsx
  app/[lang]/research/page.tsx
  app/shared/components/Quote/Quote.styles.ts
  app/shared/components/Quote/Quote.tsx
  app/shared/components/research-and-scientific-work/ResearchAndScientificWork.test.tsx
  app/shared/components/research-and-scientific-work/ResearchAndScientificWork.tsx
  app/shared/components/title-with-quote/TitleWithQuote.styles.ts
  app/shared/components/title-with-quote/TitleWithQuote.test.tsx
  app/shared/components/title-with-quote/TitleWithQuote.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
  public/images/quote.svg
Labels: frontend, feature

#198 Button Group implementation
  app/shared/components/design-system/all-components/button-group/ButtonGroup.styles.ts
  app/shared/components/design-system/all-components/button-group/ButtonGroup.test.tsx
  app/shared/components/design-system/all-components/button-group/ButtonGroup.tsx
  app/shared/components/design-system/all-components/theme/Theme.ts
  app/shared/components/design-system/all-components/theme/colors.ts
  app/types/types/common.types.ts
Labels: frontend, UI/UX, feature, design system

#297 (SP: 0,5) Fix styles in 'LiatoshynskyOffice' component
  app/shared/components/Liatoshynsky-office/LiatoshynskyOffice.styles.ts
Labels: bug, frontend, UI/UX

#276 (SP:) Add vertical decorative background lines to the 'Foundation' page #245
  app/[lang]/layout.tsx
  app/globals.css
  app/shared/components/FoundationFounders/FoundationFounders.styles.ts
  app/shared/components/FoundationFounders/FoundationFounders.tsx
  app/shared/components/column-guides/ColumnGuides.style.ts
  app/shared/components/column-guides/ColumnGuides.tsx
Labels: frontend, UI/UX, feature

#289 Design System Scrollable container
  app/shared/components/design-system/all-components/scrollable/Scrollable.style.ts
  app/shared/components/design-system/all-components/scrollable/Scrollable.test.tsx
  app/shared/components/design-system/all-components/scrollable/Scrollable.tsx
Labels: frontend, feature, design system

#301 Implement Pagination component
  app/shared/components/design-system/all-components/pagination/Pagination.style.ts
  app/shared/components/design-system/all-components/pagination/Pagination.test.tsx
  app/shared/components/design-system/all-components/pagination/Pagination.tsx
  app/validators/pagination.schema.ts
Labels: frontend, feature

#302 Created LiatoshynskyWork block
  app/[lang]/work/page.test.tsx
  app/[lang]/work/page.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, UI/UX, feature

#309 (SP:) Fix UI bug in "What We Do" block
  app/shared/components/what-we-do/WhatWeDo.styles.ts
  app/shared/components/what-we-do/WhatWeDo.tsx
Labels: bug, frontend, UI/UX
