Repository Liatoshynsky-Foundation/lf-client, pull requests merged in 2025-08, with the labels that each got.

#446 fix: key prop of cells in CollapsibleRow
  app/[lang]/artistry/CompositionTable/MusicTableSelection.tsx
Labels: bug, frontend

#457 (SP:) Fix bug in UI connected with lines in the background
  app/[lang]/layout.tsx
  app/shared/components/blocks/FoundationFounders/FoundationFounders.styles.ts
Labels: bug, frontend, UI/UX

#432 Bring back address for way to pay
  app/domain/dto/foundationInfo.dto.ts
  app/infrastructure/models/foundation-info/foundationInfoContact.ts
  app/infrastructure/repositories/foundation-info/foundationInfo.repository.ts
  app/infrastructure/repositories/foundation-info/foundationInfo.test.ts
  app/services/composed/footer-service/footerService.test.ts
  app/services/composed/footer-service/footerService.ts
  app/shared/components/Footer/Footer.tsx
  app/shared/components/Footer/FooterContactInfo/FooterContactInfo.styles.ts
  app/shared/components/Footer/FooterContactInfo/FooterContactInfo.test.tsx
  app/shared/components/Footer/FooterContactInfo/FooterContactInfo.tsx
  app/validators/foundationInfo.schema.ts
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, refactoring

#450 Create cookie consent logic
  .env.example
  app/[lang]/layout.tsx
  app/shared/components/cookie-modal/CookieModalWrapper.test.tsx
  app/shared/components/cookie-modal/CookieModalWrapper.tsx
  app/shared/components/cookie-modal/modal/CookieModal.styles.ts
  app/shared/components/cookie-modal/modal/CookieModal.test.tsx
  app/shared/components/cookie-modal/modal/CookieModal.tsx
  app/shared/components/cookie-modal/preferances/CookiePreferencesModal.test.tsx
  app/shared/components/cookie-modal/preferances/CookiePreferencesModal.tsx
Labels: frontend, feature

#429 Header data fetch
  app/api/header/route.ts
  app/constants/errors.ts
  app/constants/routes/api-routes.ts
  app/constants/routes/page-routes.ts
  app/lib/utils/getFullUrl.test.ts
  app/lib/utils/getFullUrl.ts
  app/services/client/baseService.test.ts
  app/services/client/headerService.test.ts
  app/services/client/headerService.ts
  app/services/composed/header-service/headerService.ts
  app/shared/components/Header/Header.test.tsx
  app/shared/components/Header/Header.tsx
  app/shared/components/Header/RightActionsPanel/RightActionsPanel.tsx
  app/shared/components/Header/SupportButton/SupportButton.tsx
  app/shared/components/design-system/all-components/button-group/ButtonGroup.test.tsx
  app/shared/components/design-system/all-components/button-group/ButtonGroup.tsx
  app/shared/components/design-system/all-components/navigation-bar/NavigationBar.tsx
  app/shared/components/design-system/all-components/navigation-bar/dekstop-nav/DesktopNav.test.tsx
  app/shared/components/design-system/all-components/navigation-bar/dekstop-nav/DesktopNav.tsx
  app/types/types/header.type.ts
Labels: frontend, api

#466 Integrate audio player connection with artistry table
  app/[lang]/artistry/CompositionTable/MusicTableCells.tsx
  app/[lang]/artistry/CompositionTable/MusicTableSelection.tsx
  app/[lang]/layout.tsx
  app/constants/audioPlayer.ts
  app/constants/errors.ts
  app/shared/components/Header/AudioPlayer/AudioPlayer.test.tsx
  app/shared/components/Header/AudioPlayer/AudioPlayer.tsx
  app/shared/components/Header/RightActionsPanel/RightActionsPanel.tsx
  app/shared/context/AudioPlayerContext.test.tsx
  app/shared/context/AudioPlayerContext.tsx
Labels: frontend, feature, investigate

#500 Implemented contact form ui
  app/shared/components/forms/contact-form/ContactForm.styles.ts
  app/shared/components/forms/contact-form/ContactForm.test.tsx
  app/shared/components/forms/contact-form/ContactForm.tsx
  i18n/messages/en.json
  i18n/messages/uk.json
  public/icons/info-error.svg
Labels: frontend, feature

#520 feat: create a component to display TipTap content
  app/shared/components/tip-tap-content/TipTapContent.tsx
  app/shared/components/tip-tap-content/marks.tsx
  app/shared/components/tip-tap-content/nodes.tsx
  app/shared/components/tip-tap-content/renderNode.tsx
  app/shared/components/tip-tap-content/renderText.tsx
  app/types/enums/common.enums.ts
  app/types/types/common.types.ts
  eslint.config.mjs
Labels: frontend, feature, priority: high

#523 Addition of Cookie And Preference modal responsiveness
  app/shared/components/cookie-modal/modal/CookieModal.styles.ts
  app/shared/components/cookie-modal/modal/CookieModal.tsx
  app/shared/components/cookie-modal/preferances/CookiePreferencesModal.styles.ts
  app/shared/components/cookie-modal/preferances/CookiePreferencesModal.tsx
  app/shared/components/design-system/all-components/modal/Modal.styles.ts
  app/shared/components/design-system/all-components/modal/Modal.test.tsx
Labels: bug, frontend, refactoring, responsivness

#501 (SP: ) Change schema for pages in db and base back logic (now it need work with TipTap)
  app/api/blob-url/route.ts
  app/api/page/route.ts
  app/constants/errors.ts
  app/domain/dto/pagesData.dto.ts
  app/infrastructure/models/pages/pages.ts
  app/infrastructure/repositories/pages-data/pagesData.repository.ts
  app/infrastructure/repositories/pages-data/pagesData.test.ts
  app/services/composed/pages-data-service/pagesDataService.test.ts
  app/services/composed/pages-data-service/pagesDataService.ts
  app/services/strategy/blockStrategy/blockTransformStrategy.test.ts
  app/services/strategy/blockStrategy/blockTransformStrategy.ts
  app/services/strategy/blockStrategy/homePage/transformer.test.ts
  app/services/strategy/blockStrategy/homePage/transformer.ts
  app/shared/components/blocks/FoundationFounders/FoundationFounders.tsx
  app/shared/components/blocks/FoundationInfo/FoundationInfo.tsx
  app/shared/components/blocks/IntroSection/IntroSection.tsx
  app/shared/components/blocks/Liatoshynsky-office/LiatoshynskyOffice.tsx
  app/shared/components/blocks/our-goals/OurGoals.tsx
  app/shared/components/blocks/our-mission/OurMission.tsx
  app/shared/components/blocks/what-we-do/WhatWeDo.tsx
  app/types/page/about-us.ts
  app/validators/blob.schema.ts
  app/validators/page/blocks/anyBlock.schema.ts
  app/validators/page/blocks/contentConstructorBlock.schema.ts
  app/validators/page/blocks/teamBlock.schema.ts
  app/validators/page/elements/anyElement.schema.ts
  app/validators/page/elements/bulletedList.schema.ts
  app/validators/page/elements/heading.schema.ts
  app/validators/page/elements/image.schema.ts
  app/validators/page/elements/paragraph.schema.ts
  app/validators/page/elements/quote.schema.ts
  app/validators/page/elements/titledList.schema.ts
  app/validators/page/page.schema.ts
  app/validators/pagesSchemas/pages/_common.schema.ts
  app/validators/pagesSchemas/pages/about-us.schema.ts
  app/validators/pagesSchemas/pages/index.ts
  app/validators/pagesSchemas/tiptap.schema.ts
  app/validators/queryParams.schema.ts
Labels: backend, db schema, refactoring

#534 Feature/522/about us page adaptation
  app/[lang]/page.test.tsx
  app/[lang]/page.tsx
  app/infrastructure/models/pages/pages.ts
  app/shared/components/blocks/FoundationFounders/FoundationFounders.test.tsx
  app/shared/components/blocks/FoundationFounders/FoundationFounders.tsx
  app/shared/components/blocks/FoundationFounders/FoundationTeam/FoundationTeam.tsx
  app/shared/components/blocks/FoundationFounders/FoundationWasCreated/FoundationWasCreated.styles.ts
  app/shared/components/blocks/FoundationFounders/FoundationWasCreated/FoundationWasCreated.test.tsx
  app/shared/components/blocks/FoundationFounders/FoundationWasCreated/FoundationWasCreated.tsx
  app/shared/components/blocks/FoundationInfo/FoundationInfo.styles.tsx
  app/shared/components/blocks/FoundationInfo/FoundationInfo.test.tsx
  app/shared/components/blocks/FoundationInfo/FoundationInfo.tsx
  app/shared/components/blocks/IntroSection/IntroSection.tsx
  app/shared/components/blocks/Liatoshynsky-office/LiatoshynskyOffice.tsx
  app/shared/components/blocks/our-goals/OurGoals.test.tsx
  app/shared/components/blocks/our-goals/OurGoals.tsx
  app/shared/components/blocks/our-mission/OurMission.test.tsx
  app/shared/components/blocks/our-mission/OurMission.tsx
  app/shared/components/blocks/what-we-do/WhatWeDo.test.tsx
  app/shared/components/blocks/what-we-do/WhatWeDo.tsx
  app/shared/components/list-item/ListItem.tsx
  app/types/page/about-us.ts
  app/types/page/about-us.types.ts
  app/types/types/titleWithDescriptionComponent.ts
Labels: frontend, feature

#519 Add custom paper component
  app/lib/utils/sxToArray.ts
  app/shared/components/forms/contact-form/ContactForm.styles.ts
  app/shared/components/forms/contact-form/ContactForm.tsx
  app/shared/components/paper-component/PaperComponent.styles.ts
  app/shared/components/paper-component/PaperComponent.test.tsx
  app/shared/components/paper-component/PaperComponent.tsx
  app/types/types/common.types.ts
Labels: feature

#524 Connect filters to Scientific and Research table
  app/[lang]/research/WorksTable/WorkTable.constants.ts
  app/[lang]/research/WorksTable/WorkTableSelection.test.tsx
  app/[lang]/research/WorksTable/WorkTableSelection.tsx
  app/[lang]/research/page.test.tsx
  app/[lang]/research/page.tsx
  app/api/scientific-authors/route.ts
  app/infrastructure/repositories/scientific-works/scientificWorks.repository.ts
  app/shared/components/design-system/all-components/selector/FilterSelect.test.tsx
  app/shared/components/design-system/all-components/selector/FilterSelect.tsx
  app/shared/components/enhanced-table/EnhancedTable.tsx
  app/shared/components/enhanced-table/control-panel/ControlPanel.tsx
  app/shared/components/tables/WorksTable/WorkTableCells.test.tsx
  app/shared/components/tables/WorksTable/WorkTableCells.tsx
  app/shared/components/tables/WorksTable/WorkTableSelection.test.tsx
  app/shared/components/tables/WorksTable/WorkTableSelection.tsx
  app/shared/components/tables/WorksTable/filters/Filters.tsx
  app/shared/components/tables/WorksTable/filters/YearNumericFilter.tsx
  app/types/types/enhancedTable.ts
  app/validators/scientific-works/scientificWorks.schema.ts
  public/icons/trash-2.svg
Labels: frontend, feature

#543 Connect blocks from research page to db
  app/[lang]/research/page.test.tsx
  app/[lang]/research/page.tsx
  app/services/composed/pages-data-service/pagesDataService.ts
  app/shared/components/Quote/Quote.styles.ts
  app/shared/components/research-and-scientific-work/ResearchAndScientificWork.test.tsx
  app/shared/components/research-and-scientific-work/ResearchAndScientificWork.tsx
  app/types/page/research.types.ts
  app/validators/pagesSchemas/pages/index.ts
  app/validators/pagesSchemas/pages/research.schema.ts
Labels: frontend, backend, feature

#548 Privacy policy page backend
  app/infrastructure/models/pages/pages.ts
  app/services/composed/pages-data-service/pagesDataService.test.ts
  app/services/composed/pages-data-service/pagesDataService.ts
  app/validators/pagesSchemas/pages/index.ts
  app/validators/pagesSchemas/pages/privacy-policy.schema.ts
Labels: backend, feature

#558 feat: create custom backdrop component
  app/shared/components/backdrop-component/BackdropComponent.styles.ts
  app/shared/components/backdrop-component/BackdropComponent.test.tsx
  app/shared/components/backdrop-component/BackdropComponent.tsx
Labels: frontend, feature

#557 Update design for all breakpoints
  app/shared/components/Header/Header.styles.ts
  app/shared/components/Header/Header.tsx
  app/shared/components/Header/RightActionsPanel/RightActionsPanel.styles.ts
  app/shared/components/Header/RightActionsPanel/RightActionsPanel.tsx
  app/shared/components/Header/SupportButton/SupportButton.tsx
  app/shared/components/design-system/all-components/navigation-bar/NavigationBar.tsx
  app/shared/components/design-system/all-components/navigation-bar/dekstop-nav/DesktopNav.styles.ts
  app/shared/components/design-system/all-components/navigation-bar/mobile-nav/MobileNav.styles.ts
  app/shared/components/design-system/all-components/navigation-bar/mobile-nav/MobileNav.tsx
  public/icons/menu-button.svg
  public/icons/support.svg
Labels: refactoring, responsivness

#540 Implemented responsive Contacts page
  app/[lang]/contacts/ContactsInfo/ContactsInfo.styles.ts
  app/[lang]/contacts/ContactsInfo/ContactsInfo.test.tsx
  app/[lang]/contacts/ContactsInfo/ContactsInfo.tsx
  app/[lang]/contacts/page.tsx
  app/shared/components/Footer/footer-social-media/FooterSocialMedia.tsx
  app/shared/components/forms/contact-form/ContactForm.styles.ts
  i18n/messages/en.json
  i18n/messages/uk.json
Labels: frontend, feature
