Repository Liatoshynsky-Foundation/lf-client, pull requests merged in 2025-07, with the labels that each got.

#326 (SP: )Create 'health-check' endpoint and delete zod validation for env file
  app/api/health/route.ts
  app/config/index.test.ts
  app/config/index.ts
  app/constants/index.ts
  app/validators/env.schema.ts
  package-lock.json
Labels: backend, api, priority: high

#330 Simplify ci/cd workflow
  .github/workflows/blank.yml
  .github/workflows/ci-pr-to-develop.yml
Labels: DevOps

#335 Update deps from dependabot
  .github/workflows/develop_lf-client-stage.yml
Labels: DevOps

#331 (SP:) Allow modals to apply styles as a prop
  app/shared/components/design-system/all-components/modal/Modal.tsx
Labels: frontend, design system

#310 (SP:3) Composition Data Model Design
  app/[lang]/artistry/CompositionTable/MusicTable.constant.ts
  app/[lang]/artistry/CompositionTable/MusicTableCells.tsx
  app/[lang]/artistry/CompositionTable/MusicTableSelection.tsx
  app/[lang]/artistry/page.test.tsx
  app/[lang]/artistry/page.tsx
  app/di/modules/composedServices.module.ts
  app/di/modules/coreService.module.ts
  app/di/modules/repositories.module.ts
  app/domain/dto/composition.dto.ts
  app/domain/repositories/composition.repository.ts
  app/domain/services/artistry.type.ts
  app/infrastructure/models/artistry/artistryGenreData.ts
  app/infrastructure/models/artistry/artistryOpusData.ts
  app/infrastructure/models/artistry/artistryTableData.ts
  app/infrastructure/repositories/artistry/compositions.test.ts
  app/infrastructure/repositories/artistry/сompositions.repository.ts
  app/middleware/logger/logger.test.ts
  app/services/composed/artistry-service/aristry.test.ts
  app/services/composed/artistry-service/artistryService.ts
  app/services/core/compositionService.ts
  app/shared/components/enhanced-table/EnhancedTable.test.tsx
  app/shared/components/enhanced-table/EnhancedTable.tsx
  app/shared/components/enhanced-table/collapsible-row/CollapsibleRow.test.tsx
  app/shared/components/enhanced-table/collapsible-row/CollapsibleRow.tsx
  app/shared/components/enhanced-table/enhanced-table-row/EnhancedTableRow.tsx
  app/types/types/enhancedTable.ts
  app/validators/artistry/composition.schema.ts
  app/validators/artistry/genre.schema.ts
  app/validators/artistry/opus.schema.ts
  app/validators/constants.ts
  i18n/messages/en.json
  i18n/messages/uk.json
  jest.config.ts
  package-lock.json
Labels: frontend, backend, feature, db schema

#349 fix: remove margin from header
  app/shared/components/Header/Header.styles.ts
  app/shared/components/main-page-sections/about-foundation/AboutFoundation.tsx
Labels: bug, frontend, feature

#343 Add mongodb docker compose
  compose.yaml
Labels: DevOps

#355 Implemented Numeric Filtering component
  app/shared/components/colored-svg/ColoredSvg.styles.ts
  app/shared/components/design-system/all-components/filtering/numeric/NumericFiltering.styles.ts
  app/shared/components/design-system/all-components/filtering/numeric/NumericFiltering.test.tsx
  app/shared/components/design-system/all-components/filtering/numeric/NumericFiltering.tsx
  app/shared/components/design-system/all-components/slider/Slider.styles.ts
  app/shared/components/design-system/all-components/theme/Theme.ts
  app/shared/components/design-system/all-components/theme/colors.ts
  app/validators/filtering.schema.ts
  i18n/messages/en.json
  i18n/messages/uk.json
  public/icons/trash-2.svg
Labels: frontend, feature

#348 Implement carousel component
  app/shared/components/design-system/all-components/arrow-carousel/ArrowCarousel.styles.ts
  app/shared/components/design-system/all-components/arrow-carousel/ArrowCarousel.test.tsx
  app/shared/components/design-system/all-components/arrow-carousel/ArrowCarousel.tsx
  app/shared/components/design-system/all-components/carousel/Carousel.styles.ts
  app/shared/components/design-system/all-components/carousel/Carousel.test.tsx
  app/shared/components/design-system/all-components/carousel/Carousel.tsx
  public/icons/chevron-left.svg
  public/icons/chevron-right.svg
  public/images/carousel/carousel-1.png
  public/images/carousel/carousel-2.png
  public/images/carousel/carousel-3.png
  public/images/carousel/carousel-4.png
  public/images/carousel/carousel-5.png
Labels: frontend, UI/UX, feature

#356 (SP: 0.5) Fixed incorrect svg image size in footer
  app/shared/components/Footer/Footer.styles.ts
Labels: bug, frontend, UI/UX

#305 Create reusable composition sorting function
  app/lib/utils/compositionSort.test.ts
  app/lib/utils/compositionSort.ts
  app/types/types/composition.types.ts
Labels: frontend, feature

#366 test: add test for useScrollDirection hook
  app/shared/hooks/use-scroll-direction/useScrollDirection.test.ts
Labels: good first issue, frontend, test

#373 test: add test for NextLink component
  app/shared/components/design-system/all-components/link/NextLink.test.tsx
Labels: good first issue, frontend, feature

#379 Base Service implementation
  app/constants/errors.ts
  app/services/client/baseService.test.ts
  app/services/client/baseService.ts
  app/shared/exceptions/errors/responseError.ts
  app/types/types/common.types.ts
Labels: frontend, feature

#380 Replaced hardcoded typography color with theme color
  app/shared/components/design-system/all-components/breadcrumbs/BreadCrumbs.styles.tsx
Labels: frontend, UI/UX, design system

#397 (SP: 0.5) Fixed hydration error
  app/shared/components/design-system/all-components/navigation-bar/NavigationBar.tsx
Labels: bug, frontend

#399 Fix bug with unique keys on the main page
  app/shared/components/blocks/our-goals/OurGoals.tsx
  app/shared/components/blocks/what-we-do/WhatWeDo.tsx
Labels: bug, frontend

#377 Infinite style generation
  app/shared/components/Header/AudioPlayer/AudioPlayerPopover/AudioPlayerPopover.styles.ts
  app/shared/components/Header/AudioPlayer/AudioPlayerPopover/AudioPlayerPopover.tsx
Labels: bug, frontend

#404 Privacy policy hero section
  app/shared/components/blocks/privacy-policy/hero-section/PrivacyHeroSection.styles.ts
  app/shared/components/blocks/privacy-policy/hero-section/PrivacyHeroSection.test.tsx
  app/shared/components/blocks/privacy-policy/hero-section/PrivacyHeroSection.tsx
Labels: frontend, UI/UX, feature

#401 feat: implement TextBlock Component with indentation support
  app/globals.css
  app/shared/components/text-block/TextBlock.test.tsx
  app/shared/components/text-block/TextBlock.tsx
  package-lock.json
  package.json
Labels: frontend, UI/UX, feature

#403 Skewed image background component
  app/services/strategy/blockStrategy/blockTransformStrategy.test.ts
  app/shared/components/design-system/all-components/skewed-block/SkewedBlock.test.tsx
  app/shared/components/design-system/all-components/skewed-block/SkewedBlock.tsx
Labels: frontend, feature, test
